# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ios exercise' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios exercise
  pod "PagingMenuController"

  target 'ios exerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios exerciseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
